apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: local-postgres-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgres
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values: [asic-api, asic-migration]
      ports:
        - {protocol: TCP, port: 5432}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: local-api-postgres-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: asic-api
  policyTypes: [Egress]
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgres
      ports:
        - {protocol: TCP, port: 5432}
