apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: local-maintenance-postgres-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgres
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: asic-retention
      ports:
        - {protocol: TCP, port: 5432}
