"""telemetry ingestion

Revision ID: 0006_telemetry_ingestion
Revises: 0005_seed_ro_catalogue
Create Date: 2026-09-11 08:40:47.135258
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0006_telemetry_ingestion"
down_revision: str | None = "0005_seed_ro_catalogue"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = ("signal_receipt", "investigation_dispatch")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "investigation_dispatch",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("workflow_run_id", sa.UUID(), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.String(length=64), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempts >= 0", name=op.f("ck_investigation_dispatch_attempts_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "event_id"],
            ["incident_event.tenant_id", "incident_event.id"],
            name="fk_investigation_dispatch_event",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "incident_id"],
            ["incident.tenant_id", "incident.id"],
            name="fk_investigation_dispatch_incident",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "workflow_run_id"],
            ["workflow_run.tenant_id", "workflow_run.id"],
            name="fk_investigation_dispatch_run",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_investigation_dispatch_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_investigation_dispatch")),
        sa.UniqueConstraint("tenant_id", "event_id", name="uq_investigation_dispatch_event"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_investigation_dispatch_tenant_id_id"),
        sa.UniqueConstraint("tenant_id", "incident_id", name="uq_investigation_dispatch_incident"),
    )
    op.create_index(
        op.f("ix_investigation_dispatch_tenant_id"),
        "investigation_dispatch",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "signal_receipt",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("connector_id", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("delivery_key", sa.String(length=64), nullable=False),
        sa.Column("content_digest", sa.String(length=64), nullable=False),
        sa.Column("raw_digest", sa.String(length=64), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("alert_id", sa.UUID(), nullable=True),
        sa.Column("incident_id", sa.UUID(), nullable=True),
        sa.Column("service_id", sa.UUID(), nullable=True),
        sa.Column("environment_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("envelope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("decision", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('alert', 'change', 'invalid')", name=op.f("ck_signal_receipt_known_kind")
        ),
        sa.CheckConstraint(
            "outcome IN ('accepted', 'rejected', 'stale', 'unchanged')",
            name=op.f("ck_signal_receipt_known_outcome"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "alert_id"],
            ["alert.tenant_id", "alert.id"],
            name="fk_signal_receipt_alert",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "environment_id"],
            ["environment.tenant_id", "environment.id"],
            name="fk_signal_receipt_environment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "incident_id"],
            ["incident.tenant_id", "incident.id"],
            name="fk_signal_receipt_incident",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "service_id"],
            ["service.tenant_id", "service.id"],
            name="fk_signal_receipt_service",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_signal_receipt_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signal_receipt")),
        sa.UniqueConstraint("tenant_id", "delivery_key", name="uq_signal_receipt_delivery"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_signal_receipt_tenant_id_id"),
    )
    op.create_index(
        "ix_signal_receipt_changes",
        "signal_receipt",
        ["tenant_id", "environment_id", "service_id", "observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_signal_receipt_tenant_id"), "signal_receipt", ["tenant_id"], unique=False
    )
    op.add_column("alert", sa.Column("source_state", sa.String(length=16), nullable=True))
    op.add_column(
        "alert", sa.Column("source_observed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("alert", sa.Column("source_digest", sa.String(length=64), nullable=True))
    op.add_column("alert", sa.Column("correlation_category", sa.String(length=255), nullable=True))
    op.create_check_constraint(
        op.f("ck_alert_known_source_state"), "alert", "source_state IN ('firing', 'resolved')"
    )
    for table in TENANT_TABLES:
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table} TO asic_app")
        op.execute(f"GRANT SELECT ON {table} TO asic_auditor")
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            "USING (tenant_id = app.current_tenant_id()) "
            "WITH CHECK (tenant_id = app.current_tenant_id())"
        )
    op.execute("REVOKE UPDATE, DELETE ON signal_receipt FROM asic_app")


def downgrade() -> None:
    # Refuse loss of Phase 5 delivery/dispatch history. No FK weakening for convenience.
    # Fail closed if migration credentials cannot inspect FORCE-RLS history.
    op.execute("SET LOCAL row_security = off")
    op.execute("""DO $$ BEGIN
        IF EXISTS (SELECT 1 FROM signal_receipt) OR EXISTS (SELECT 1 FROM investigation_dispatch)
        THEN RAISE EXCEPTION 'Phase 5 history exists; downgrade refused'; END IF;
        END $$""")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_alert_known_source_state"), "alert", type_="check")
    op.drop_column("alert", "correlation_category")
    op.drop_column("alert", "source_digest")
    op.drop_column("alert", "source_observed_at")
    op.drop_column("alert", "source_state")
    op.drop_index(op.f("ix_signal_receipt_tenant_id"), table_name="signal_receipt")
    op.drop_index("ix_signal_receipt_changes", table_name="signal_receipt")
    op.drop_table("signal_receipt")
    op.drop_index(op.f("ix_investigation_dispatch_tenant_id"), table_name="investigation_dispatch")
    op.drop_table("investigation_dispatch")
    # ### end Alembic commands ###
