"""Declarative base, naming conventions and the mixins that carry tenancy.

Two decisions here shape every table in the schema.

**Constraint naming is explicit.** Alembic compares constraints by name; letting
PostgreSQL invent them makes autogenerated migrations unstable and makes a dropped
constraint hard to spot in review.

**Tenant scoping is a mixin, not a convention.** Every tenant-scoped table gets its
``tenant_id`` column, its ``(tenant_id, id)`` unique constraint and its RLS marker from
:class:`TenantScoped`. The unique constraint is what makes *composite* foreign keys
possible, and composite foreign keys are what make a cross-tenant reference structurally
impossible rather than merely unlikely:

.. code-block:: text

    FOREIGN KEY (tenant_id, incident_id) REFERENCES incident (tenant_id, id)

A child row cannot point at a parent belonging to another tenant, because the tenant is
part of the key being matched. This is the layer that survives an application bug.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import StrEnum
from typing import Any, ClassVar, Final

import sqlalchemy as sa
from sqlalchemy import MetaData
from sqlalchemy.dialects import postgresql as pg
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

#: Deterministic constraint names. ``column_0_N_name`` covers multi-column constraints.
NAMING_CONVENTION: Final[dict[str, str]] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata_obj: Final[MetaData] = MetaData(naming_convention=NAMING_CONVENTION)


class Base(DeclarativeBase):
    """Declarative base for every mapped class.

    Deliberately declares **no** ``__tenant_scoped__`` or ``__append_only__`` default.
    Because ``Base`` precedes the mixins in each model's MRO, a default here would shadow
    :class:`TenantScoped`'s ``True`` and silently mark every table as global - which would
    then silently skip row-level security for all of them. Callers use
    ``getattr(cls, "__tenant_scoped__", False)`` instead, so the flag can only ever be set
    by the mixin or by an explicit declaration in the model body.
    """

    metadata = metadata_obj


def enum_column(
    enum_cls: type[StrEnum],
    name: str,
    **kwargs: Any,
) -> sa.Enum:
    """Native PostgreSQL ``ENUM`` backed by a Python :class:`~enum.StrEnum`.

    ``values_callable`` stores the member *values* (``"awaiting_approval"``) rather than
    the member *names* (``"AWAITING_APPROVAL"``), so the database contains the vocabulary
    the documentation and the API use.
    """
    return sa.Enum(
        enum_cls,
        name=name,
        native_enum=True,
        create_constraint=False,
        validate_strings=True,
        values_callable=lambda e: [member.value for member in e],
        **kwargs,
    )


def uuid_pk() -> Mapped[uuid.UUID]:
    return mapped_column(
        pg.UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=sa.text("gen_random_uuid()"),
    )


class TimestampMixin:
    """``created_at`` / ``updated_at``, both database-generated.

    Times come from the database rather than the application so that rows written by
    different processes with different clocks remain comparable.
    """

    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
        onupdate=sa.func.now(),
    )


class CreatedAtMixin:
    """``created_at`` only - for append-only tables, where ``updated_at`` would be a lie."""

    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
    )


class OptimisticLockMixin:
    """Row version for optimistic concurrency.

    Applied to the few entities where two writers legitimately race and last-write-wins
    would lose a decision: incident status and remediation action status. SQLAlchemy
    raises :class:`~sqlalchemy.orm.exc.StaleDataError` when a concurrent update is
    detected, which the caller must resolve by re-reading rather than retrying blindly.
    """

    version_id: Mapped[int] = mapped_column(sa.Integer, nullable=False, default=1)

    __mapper_args__: ClassVar[dict[str, Any]] = {"version_id_col": None}


class TenantScoped:
    """Tenant ownership, the ``(tenant_id, id)`` key, and the RLS marker.

    Any table mixing this in is included in the row-level security migration. The
    ``__tenant_scoped__`` flag is asserted against the live database by the test suite, so
    a new tenant-scoped table that is not protected fails the build.
    """

    __tenant_scoped__: ClassVar[bool] = True

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        pg.UUID(as_uuid=True),
        sa.ForeignKey("tenant.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )


def tenant_identity_constraints(table_name: str) -> tuple[sa.UniqueConstraint, ...]:
    """The ``(tenant_id, id)`` uniqueness that composite foreign keys reference."""
    return (
        sa.UniqueConstraint(
            "tenant_id",
            "id",
            name=f"uq_{table_name}_tenant_id_id",
        ),
    )


def tenant_fk(
    local_column: str,
    referred_table: str,
    *,
    ondelete: str = "CASCADE",
    name: str | None = None,
) -> sa.ForeignKeyConstraint:
    """Composite foreign key that carries the tenant through the reference.

    Use this in place of a plain single-column foreign key for every reference between
    tenant-scoped tables. It is the mechanism that makes INV-1 ("no cross-tenant
    reference") a database guarantee.
    """
    return sa.ForeignKeyConstraint(
        ["tenant_id", local_column],
        [f"{referred_table}.tenant_id", f"{referred_table}.id"],
        ondelete=ondelete,
        name=name,
    )


#: JSONB with a sane default, used for payloads, arguments and structured metadata.
def jsonb_column(*, nullable: bool = False, default_empty: bool = True) -> Mapped[Any]:
    return mapped_column(
        pg.JSONB,
        nullable=nullable,
        server_default=sa.text("'{}'::jsonb") if default_empty and not nullable else None,
    )
